export const ROUTES = {
  HOME: "/",
  SIGN_UP: "/sign-up",
  SIGN_IN: "/sign-in",
  PRICING: "/pricing",
  WATCH: "/watch",
  HISTORY: "/playlist/history",
  SETTINGS: "/settings",
  HELP: "/blog/help",
  LIKED_VIDEOS: "/playlist/liked-videos",
  YOUR_VIDEOS: "/profile-videos",
  LIBRARY: "/profile-playlists",
  FOLLOWING: "/profile-following",
  CREATOR_STUDIO: "/dashboard",
  TOS: "/blog/tos",
  PRIVACY: "/blog/privacy",
};
